runtime: nodejs20

env_variables:
  # Gemini AI Configuration
  API_KEY: "AIzaSyDu61sbhChm3wJpEZ80rJ9zH8uwP__EoiI"
  GEMINI_API_KEY: "AIzaSyDu61sbhChm3wJpEZ80rJ9zH8uwP__EoiI"
  USE_GEMINI: "true"
  
  # Circle Wallet Configuration
  CIRCLE_API_KEY: "TEST_API_KEY:04cf0bd526bed6c1d30c5f678ac2f44d:04d9de879785c379d385f3ef230bfdc6"
  CIRCLE_ENTITY_SECRET: "be56ba78224ea771f5c893622a684d98b52e6fd726e2fd8530608778dcd5e47d"
  AGENT_WALLET_ID: "4bfac53b-550d-5059-bbb3-9c7ba13b5be1"
  AGENT_WALLET_ADDRESS: "0x6a485cf0a928ed2a8090bd91fa9f01bda56a3333"
  SECONDARY_WALLET_ID: "0f43a141-83f1-5a9e-b13e-efd4518cb74f"
  SECONDARY_WALLET_ADDRESS: "0xc7f3ba92fdb5541fc4eec5521f009c61dc5f6021"
  WALLET_SET_ID: "585151ae-e0d0-5347-9f52-fbc5b16679fa"
  USE_CIRCLE: "true"
  
  # Server Configuration
  PORT: "8080"
  NODE_ENV: "production"
  
  # Policy Configuration
  MAX_TRANSACTION_AMOUNT_USDC: "100"
  DAILY_SPENDING_LIMIT_USDC: "1000"
  WEEKLY_BUDGET_USDC: "1000"
  MONTHLY_BUDGET_USDC: "5000"

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
- url: /.*
  script: auto
  secure: always